export const Barangays = [
    'Bagong Pook',
    'Bagumbayan',
    'Balayong',
    'Bubukal',
    'Cabooan',
    'Calangay',
    'Cambuja',
    'Coralan',
    'Cueva',
    'Inayapan',
    'Jose Laurel Sr.',
    'Jose Rizal',
    'Juan Santiago',
    'Kayrilaw',
    'Macasipac',
    'Masinao',
    'Mataling-Ting',
    'Parang ng Buho',
    'Poblacion Uno',
    'Poblacion Dos',
    'Poblacion Tres',
    'Poblacion Cuatro',
    'San Gabriel',
    'San Jose Malaking Tubig',
    'San Miguel',
    'Santa Clara',
    'Santa Cruz',
    'Santo Tomas',
    'Silangan',
];

export const ID_TYPES = [
    'driversLicense',
    'passport',
    'umid',
    'sss',
    'philhealth',
    'votersId',
    'postalId',
    'barangayId',
];